#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME 
use_node_port=""
if [ "$NODE_PORT" = true ]; then
    use_node_port="--set gateways.istio-ingressgateway.type=NodePort"
fi

case $action in
    install)
        echo "Installing helm client"
        helm init --client-only

        echo "Installing Istio"
        helm install -n istio /charts/istio*.tgz --namespace istio-system ${use_node_port} --wait

        echo "Installing riff"
        helm install -n riff /charts/riff*.tgz
        ;;
    uninstall)
        echo "uninstall action"
        helm delete --purge riff
        helm delete --purge istio
        kubectl get crd -o name | grep -E "(istio|projectriff|knative)" | xargs kubectl delete
        ;;
    upgrade)
        echo "Upgrade action"
        echo "not supported yet"
        ;;
    status)
        echo "Status action"
        helm status istio
        helm status riff
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
